# Network Architecture for RoCE (RDMA over Converged Ethernet)
# This configuration is designed to support a high-performance network setup
# for GPU traffic using x8 GPUs and x8 NICs. Each NIC is configured with a 
# static IP address that corresponds to its device name, ensuring efficient 
# and parallel data transfer between GPUs and NICs. The ens51f0np0 and 
# ens51f1np1 interfaces are configured to use DHCP for IPv4 to allow dynamic 
# IP assignment for external customer traffic. The MTU is set to 9100 to support jumbo frames, which is 
# essential for high-throughput, low-latency communication in RoCE environments.

network:
  version: 2
  ethernets:
    ens11np0:
      addresses:
        - 192.168.11.1/24
      routes:
        - to: default
          via: 192.168.11.254
          table: 101
      routing-policy:
        - from: 192.168.11.1
          table: 101
      mtu: 9100
      match:
        macaddress: d4:04:e6:78:03:84
      optional: true

    ens12np0:
      addresses:
        - 192.168.12.1/24
      routes:
        - to: default
          via: 192.168.12.254
          table: 102
      routing-policy:
        - from: 192.168.12.1
          table: 102
      mtu: 9100
      match:
        macaddress: d4:04:e6:0e:8a:38
      optional: true

    ens21np0:
      addresses:
        - 192.168.21.1/24
      routes:
        - to: default
          via: 192.168.21.254
          table: 103
      routing-policy:
        - from: 192.168.21.1
          table: 103
      mtu: 9100
      match:
        macaddress: d4:04:e6:0e:87:54
      optional: true

    ens22np0:
      addresses:
        - 192.168.22.1/24
      routes:
        - to: default
          via: 192.168.22.254
          table: 104
      routing-policy:
        - from: 192.168.22.1
          table: 104
      mtu: 9100
      match:
        macaddress: d4:04:e6:0e:93:c0
      optional: true

    ens31np0:
      addresses:
        - 192.168.31.1/24
      routes:
        - to: default
          via: 192.168.31.254
          table: 105
      routing-policy:
        - from: 192.168.31.1
          table: 105
      mtu: 9100
      match:
        macaddress: d4:04:e6:0e:79:d0
      optional: true

    ens32np0:
      addresses:
        - 192.168.32.1/24
      routes:
        - to: default
          via: 192.168.32.254
          table: 106
      routing-policy:
        - from: 192.168.32.1
          table: 106
      mtu: 9100
      match:
        macaddress: d4:04:e6:0e:9b:04
      optional: true

    ens41np0:
      addresses:
        - 192.168.41.1/24
      routes:
        - to: default
          via: 192.168.41.254
          table: 107
      routing-policy:
        - from: 192.168.41.1
          table: 107
      mtu: 9100
      match:
        macaddress: d4:04:e6:0e:9c:80
      optional: true

    ens42np0:
      addresses:
        - 192.168.42.1/24
      routes:
        - to: default
          via: 192.168.42.254
          table: 108
      routing-policy:
        - from: 192.168.42.1
          table: 108
      mtu: 9100
      match:
        macaddress: d4:04:e6:0e:84:c0
      optional: true

    ens50f0:
      addresses:
        - 192.168.50.1/24
      routes:
        - to: default
          via: 192.168.50.254
          table: 109
      routing-policy:
        - from: 192.168.50.1
          table: 109
      mtu: 9100
      match:
        macaddress: 3c:ec:ef:e1:96:a4
      optional: true

    ens50f1:
      addresses:
        - 192.168.51.1/24
      routes:
        - to: default
          via: 192.168.51.254
          table: 110
      routing-policy:
        - from: 192.168.51.1
          table: 110
      mtu: 9100
      match:
        macaddress: 3c:ec:ef:e1:96:a5
      optional: true

    ens51f0np0:
      # DHCP configuration for ens51f0np0
      dhcp4: true
      dhcp6: false
      mtu: 9100
      match:
        macaddress: d4:04:e6:e9:39:c0

    ens51f1np1:
      # DHCP configuration for ens51f1np1
      dhcp4: true
      dhcp6: false
      mtu: 9100
      match:
        macaddress: d4:04:e6:e9:39:c1

    usb0:
      addresses:
        - 192.168.60.1/24
      routes:
        - to: default
          via: 192.168.60.254
          table: 111
      routing-policy:
        - from: 192.168.60.1
          table: 111
      mtu: 9100
      match:
        macaddress: 00:00:00:00:00:00
